[profile.default]
solc-version = '0.8.22'
src = 'contracts'
out = 'out'
test = 'test'
cache_path = 'cache'
libs = ["lib"]

[rpc_endpoints]
sepolia = "https://rpc2.sepolia.org"
scroll = "https://scroll-sepolia.chainstacklabs.com"
scroll2 = "https://sepolia-rpc.scroll.io"
polygon = "https://rpc-amoy.polygon.technology"
zircuit = "https://zircuit1-testnet.p2pify.com"


unichain = "https://sepolia.unichain.org"
arbitrumSepolia = "https://sepolia-rollup.arbitrum.io/rpc"
optimismSepolia = "https://sepolia.optimism.io"
polygonZkEvm = "https://zkevm-rpc.com"
polygonZkEvmTestnet = "https://rpc.public.zkevm-test.net"
baseSepolia = "https://sepolia.base.org"
pgnTestnet = "https://sepolia.publicgoods.network"
